### ISSUE TITLE
API Doc Generate

### ISSUE THREAD

**Issue by rafsAcorsi** [joshfriend/flask-restful-demo#4]
Hello Josh, very good your work, I have a question that maybe you can help me.
How do you generate a documentation of its API?

**Comment by joshfriend** [comment]
Look at [Apiary](https://apiary.io/) or [Swagger](http://swagger.io/). Neither is autogenerated from the python source of the Flask application, but are both good tools. Personally, I use Apiary.

**Comment by rafsAcorsi** [comment]
Thank you Josh.
